name = "BetterFileWatching"
uuid = "c9fd44ac-77b5-486c-9482-9798bd063cc6"
authors = ["Fons van der Plas <fons@plutojl.org>"]
version = "0.1.5"

[deps]
libwatcher_jll = "f2e3f4ed-6d30-53f6-bb33-6a6ab454fa9c"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
