name = "BetterFileWatching"
uuid = "c9fd44ac-77b5-486c-9482-9798bd063cc6"
authors = ["Fons van der Plas <fons@plutojl.org>"]
version = "0.2.0"

[deps]
CancellationTokens = "2e8d271d-f2e2-407b-a864-17eb2156783e"
FileWatching = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"

[compat]
CancellationTokens = "2.3"
FileWatching = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
