name: Julia tests

on:
    workflow_dispatch:
    push:
        paths-ignore:
            - '**.md'
        branches:
            - main
    pull_request:
        paths-ignore:
            - '**.md'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    test:
        name: Julia ${{ matrix.julia-version }} — ${{ matrix.os }}
        timeout-minutes: 30
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                julia-version: ['1.10', '1']
                os: [ubuntu-latest, macOS-latest, windows-latest]
                include:
                    - os: ubuntu-latest
                      julia-version: 'nightly'
        continue-on-error: ${{ matrix.julia-version == 'nightly' }}

        steps:
            - uses: actions/checkout@v7

            - uses: julia-actions/setup-julia@v3
              with:
                  version: ${{ matrix.julia-version }}

            - uses: julia-actions/cache@v2

            - uses: julia-actions/julia-buildpkg@v1

            - uses: julia-actions/julia-runtest@v1
